substitutions:
  device_name: bedroom_m5stick
  device_description: Bedroom M5Stick
  friendly_name: Bedroom M5Stick

# Enable Home Assistant API
api:
  encryption:
    key: "MrfxRs9126MhJnIEIBs4rX+Q9Lp9d1tJy82Be9yiYh0="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: # since we listed an SSID above, this AP mode will only enable if no WiFi connection could be made
    ssid: ${friendly_name}_AP
    password: !secret wifi_password

sensor:
  # Reports the WiFi signal strength
  - platform: wifi_signal
    name: ${friendly_name} Signal Strength
    update_interval: 60s
  # Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

binary_sensor:
  # Reports if this device is Connected or not
  - platform: status
    name: ${friendly_name} Status

text_sensor:
  # Reports the ESPHome Version with compile date
  - platform: version
    name: ${friendly_name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
    ssid:
      name: ${friendly_name} SSID
    bssid:
      name: ${friendly_name} BSSID
  - platform: wifi_signal
    name: ${friendly_name} Wifi Strength
    update_interval: 60s

button:
  - platform: restart
    name: "${friendly_name} Restart"

external_components:
  - source:
      type: git
      url: https://gitlab.com/geiseri/esphome_extras.git
    refresh: 1d
    components: [axp192]

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

time:
  - platform: homeassistant
    id: homeassistant_time

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true
  - id: bus_b
    sda: 32
    scl: 33
    scan: true

axp192:
  id: axp
  address: 0x34
  i2c_id: bus_a
  update_interval: 60s

sensor:
  - platform: axp192
    axp192_id: axp
    id: ${device_name}batterylevel
    name: ${friendly_name} Battery Level

output:
  - platform: gpio
    pin: 10
    id: red_led

light:
  - platform: monochromatic
    id: red_led_light
    name: "${friendly_name} Red LED"
    output: red_led

on_boot:
  then:
    - light.turn_on:
      id: red_led_light
      brightness: 100%
      transition_length: 0s
